config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root "todo_lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  default_scope -> { order('completed_at asc').order('id DESC') }
  validates :content, presence: true
  def completed?
    !completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todo_items
  default_scope -> { order('id DESC') }
  validates :title, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :find_todo_list
  before_action :find_todo_item, except: [:create]

  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    redirect_to @todo_list
  end

  def destroy
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.destroy
      flash[:success] = "Todo List item was deleted."
    else
      flash[:error] = "Todo List item could not be deleted."
    end
    redirect_to @todo_list
  end
  
  def complete
		@todo_item.update_attribute(:completed_at, Time.now)
		redirect_to @todo_list, notice: "Todo item completed"
  end
  
  private

  def find_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

	def find_todo_item
		@todo_item = @todo_list.todo_items.find(params[:id])
	end

  def todo_item_params
    params.require(:todo_item).permit(:content)
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :find_todo_list, only: [:show, :edit, :update, :destroy]

  def index
    @todo_lists = TodoList.all
  end

  def show
  end

  def new
    @todo_list = TodoList.new
  end

  def edit
  end

  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to todo_lists_path, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo_list.todo_items.destroy_all
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_path, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def find_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo List APP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-sm-12 col-md-10 col-lg-8 mt-5">
          <div class="card card-deco">
            <% if notice %>
              <div class="alert-deco alert alert-light text-center text-info mb-0" role="alert">
                <%= notice %>
              </div>
            <% end  %>
            <%= yield %>
          <div>
        <div>
      <div>
    </div>
  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_with model: [@todo_list, @todo_list.todo_items.build], class: 'form-inline d-inline-block' do |form| %>
  <%= form.text_field :content, placeholder: "Add New Task", class: 'form-control form-control-deco mr-2' %>

  <%= form.submit 'Create Task', class: 'btn btn-outline-secondary' %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<tbody>
    <% if todo_item.completed? %>  
  <tr>
      <td class="text-center font-weight-light text-muted align-middle pr-0 complete-task-deco">
        <i class="text-secondary fa fa-check-circle"></i>
      </td>
      <td class="font-weight-light text-break task-content text-muted align-middle complete-task-deco">
        <s><%= todo_item.content %></s>
      </td>
      <td class="text-right align-middle complete-task-deco">
        <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: 'delete',data: {confirm: 'Are you sure?'}, class: 'trash-button' do %>
          <i class="fas fa-trash-alt complete-trash"></i>
        <% end %>
      </td>
      </tr>
    <% else %>
    <tr class="uncomplete-task-deco">
      <td class="text-center align-middle h6 pr-0">
        <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch, class: 'check-button' do %>
          <i class="fa fa-check-circle"></i>
        <% end %>
      </td>
      <td class="text-break task-content align-middle h6">
        <%= todo_item.content %>
      </td>
      <td class="text-right align-middle">
        <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: 'delete',data: {confirm: 'Are you sure?'}, class: 'trash-button' do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </td>
  </tr>
    <% end %>
</tbody>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div class="alert">
      <span class="font-weight-bold"><%= pluralize(todo_list.errors.count, "item") %> Please Check again!</span><br>
      <% todo_list.errors.full_messages.each do |message| %>
        <span class="error-message-text"><%= message %></span><br>
      <% end %>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control form-control-deco' %>
  </div>

  <div class="field form-group mb-3">
    <%= form.label :description %>
    <%= form.text_area :description, rows: "5", class: 'form-control form-control-deco' %>
  </div>

  <div class="actions text-right">
    <%= form.submit class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<div class="card-body">
  <h5 class="card-title text-center">
    Edit Todo List
  </h5>
</div>
<div class="card-body">
  <%= render 'form', todo_list: @todo_list %>
</div>
<%= link_to 'Cancel', @todo_list, method: 'delete',data: {confirm: 'Maybe lots of tasks in here.    Are you sure?'}, class: 'btn-light card-footer text-center text-decoration-none mt-4 font-weight-light' %>
<%= link_to 'Back', @todo_list, class: 'btn-light card-footer text-center text-decoration-none font-weight-bold' %>

app/views/todo_lists/index.html.erb
<div class="card-body">
	<h5 class="card-title text-center">My Todo Lists</h5>
</div>
<ul class="list-group list-group-flush">
	<% @todo_lists.each do |todo_list| %>
		<%= link_to todo_list, class: 'text-decoration-none' do %>
			<li class="list-group-item list-group-item-deco">
				<span class="list-title font-weight-bold d-block"><%= truncate todo_list.title, length: 30 %><br></span>
				<span class="font-weight-lighter list-description"><%= truncate todo_list.description, length: 43 %></span>
			</li>
		<% end %>
	<% end %>
</ul>

<%= link_to 'New Todo List', new_todo_list_path, class: 'btn-light card-footer text-center text-decoration-none' %>

app/views/todo_lists/new.html.erb
<div class="card-body">
  <h5 class="card-title text-center">
    New Todo List
  </h5>
</div>
<div class="card-body">
  <%= render 'form', todo_list: @todo_list %>
</div>

<%= link_to 'Back', todo_lists_path, class: 'btn-light card-footer text-center text-decoration-none' %>

app/views/todo_lists/show.html.erb
<div class="card-body text-center mb-3">
  <h5 class="card-title">
    <%= @todo_list.title %>
    <%= link_to edit_todo_list_path(@todo_list), class: 'edit-icon ml-1' do %>
      <small><i class="fas fa-pencil-alt"></i></small>
    <% end %>
  </h5>
  <p class="card-text">
    <%= @todo_list.description %>
  </p>
</div>

<table class="table">
  <%= render @todo_list.todo_items %>
</table>

<div class="text-center card-body">
  <%= render "todo_items/form" %>
</div>

<%= link_to 'Back', todo_lists_path, class: 'btn-light card-footer text-center text-decoration-none' %>